INSERT INTO hash_tags (tag_name, date_created, last_updated)
VALUES
    ('fashion', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('style', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('outfit', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('clothing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('accessories', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('trend', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('casual', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('elegant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('luxury', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('minimalist', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
